### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by BitonicDev** [crpmax/minecraft-bot-flood#2]
Do I have the right php?
it's saying this in command prompt:
Fatal error: Uncaught Error: Call to undefined function openssl_random_pseudo_bytes() in C:\Users\Schad\Desktop\mcbot.php:39
Stack trace:
#0 {main}
  thrown in C:\Users\Schad\Desktop\mcbot.php on line 39

my command was: php C:\Users\Schad\Desktop\mcbot.php 127.0.0.1 25565 100
file name was: mcbot.php

**Comment by crpmax** [comment]
Hello,
it looks like you don't have the OpenSSL extension active in PHP.

You can follow instructions here on how to enable it:
https://stackoverflow.com/questions/11212808/fatal-error-call-to-undefined-function-openssl-random-pseudo-bytes
https://www.php.net/manual/en/openssl.installation.php

Alternatively, you can rewrite the code and use any other function to generate the random string.
https://stackoverflow.com/questions/4356289/php-random-string-generator

**Comment by XynthX** [comment]
thanks it works

**Comment by BitonicDev** [comment]
IDK how to follow the instructions so I'll just use the new one

**Comment by crpmax** [comment]
Updated - 3d07139b52fccae7c5c4e55ad50a841dc098a4b6
Now it should work without openssl
