### ISSUE TITLE
can't

### ISSUE THREAD

**Issue by BitonicDev** [crpmax/minecraft-bot-flood#3]
i can't figure out how to recode it to not use openssl to generate, and i cant figure out how to enable openssl
can u recode the name generation to not use openssl

**Comment by terrified9** [comment]
can

**Comment by XynthX** [comment]
? can?

**Comment by BitonicDev** [comment]
> can

wdym

**Comment by crpmax** [comment]
I have already done it 2 hours ago.
3d07139b52fccae7c5c4e55ad50a841dc098a4b6
Just download the latest source.
